name: "CI/CD Pipeline for Go"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-pipeline:
    uses: guillipa1993/devops-pipelines-ci-cd/.github/workflows/go-ci.yml@main
    with:
      language: 'go'
      python-version: '1.20'
      report-language: 'English'
      project-path: './src'
      requirements-path: './requirements'
      build-configuration: 'Release'
      additional-install-commands: ''
      build-command: 'go build -o output/app ./...'
      run-check-code-format: true
      run-code-analysis: true
      run-lint: true
      environment-variables: 'GOENV=production'
    secrets:
      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}