name: "CI/CD Pipeline for .NET"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-pipeline:
    uses: guillipa1993/devops-pipelines-ci-cd/.github/workflows/dotnet-ci.yml@main
    with:
      language: 'dotnet'
      dotnet-version: '7.0'
      report-language: 'English'
      project-path: './src'
      requirements-path: ''
      build-configuration: 'Release'
      additional-install-commands: ''
      build-command: 'dotnet build ./src -c Release'
      run-check-code-format: true
      run-code-analysis: true
      run-lint: true
      environment-variables: 'DOTNET_ENV=Production'
    secrets:
      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}